"""
Silver Data Generation Module for Rosetta AI.

Uses an LLM as a "teacher" to generate synthetic parallel translation pairs at scale
across all 12 directional language pairs (Python, Java, C++, JavaScript).

All records generated by this module are explicitly tagged with:
- is_gold: False
- source_dataset: "silver_llm_teacher"
"""

import argparse
import json
import logging
import os
from pathlib import Path
from typing import Dict, List, Any, Tuple

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger("RosettaAI.DataPipeline.SilverGeneration")

CURATED_DATA_DIR = Path("data/curated")
OUTPUT_SILVER_FILE = CURATED_DATA_DIR / "silver_pairs.jsonl"

LANGUAGES = ["python", "java", "cpp", "javascript"]
DIRECTIONS = [
    (src, tgt) for src in LANGUAGES for tgt in LANGUAGES if src != tgt
]

# Estimated API costs per 1,000,000 tokens (USD)
MODEL_PRICING = {
    "gpt-4o": {"input": 2.50, "output": 10.00},
    "gpt-4o-mini": {"input": 0.15, "output": 0.60},
    "claude-3-5-sonnet": {"input": 3.00, "output": 15.00},
    "gemini-1.5-flash": {"input": 0.075, "output": 0.30},
    "gemini-1.5-pro": {"input": 1.25, "output": 5.00},
    "gemini-2.0-flash": {"input": 0.10, "output": 0.40},
}



def calculate_cost_estimate(num_pairs_per_direction: int = 100, model: str = "gpt-4o-mini") -> Dict[str, Any]:
    """
    Calculates estimated pair count, token usage, and API cost for silver data generation.
    """
    total_directions = len(DIRECTIONS)  # 12 directions
    total_pairs = num_pairs_per_direction * total_directions
    
    # Average function length: ~250 prompt tokens, ~250 completion tokens per translation
    prompt_tokens_per_pair = 250
    completion_tokens_per_pair = 250

    total_prompt_tokens = total_pairs * prompt_tokens_per_pair
    total_completion_tokens = total_pairs * completion_tokens_per_pair

    pricing = MODEL_PRICING.get(model, MODEL_PRICING["gpt-4o-mini"])
    input_cost = (total_prompt_tokens / 1_000_000) * pricing["input"]
    output_cost = (total_completion_tokens / 1_000_000) * pricing["output"]
    total_cost = input_cost + output_cost

    return {
        "num_pairs_per_direction": num_pairs_per_direction,
        "total_directions": total_directions,
        "total_pairs": total_pairs,
        "model": model,
        "estimated_prompt_tokens": total_prompt_tokens,
        "estimated_completion_tokens": total_completion_tokens,
        "estimated_input_cost_usd": round(input_cost, 4),
        "estimated_output_cost_usd": round(output_cost, 4),
        "total_estimated_cost_usd": round(total_cost, 4),
        "direction_breakdown": {f"{src}->{tgt}": num_pairs_per_direction for src, tgt in DIRECTIONS}
    }


def generate_mock_silver_pairs(num_pairs_per_direction: int = 100) -> List[Dict[str, Any]]:
    """
    Generates mock silver parallel records for testing and scaffolding without API calls.
    """
    records = []
    
    templates = {
        ("python", "java"): ("def add(a, b):\n    return a + b", "public class Add {\n    public static int add(int a, int b) {\n        return a + b;\n    }\n}"),
        ("python", "cpp"): ("def add(a, b):\n    return a + b", "int add(int a, int b) {\n    return a + b;\n}"),
        ("python", "javascript"): ("def add(a, b):\n    return a + b", "function add(a, b) {\n    return a + b;\n}"),
        ("java", "python"): ("public static int max(int a, int b) { return a > b ? a : b; }", "def max(a, b):\n    return a if a > b else b"),
        ("java", "cpp"): ("public static int max(int a, int b) { return a > b ? a : b; }", "int max(int a, int b) {\n    return a > b ? a : b;\n}"),
        ("java", "javascript"): ("public static int max(int a, int b) { return a > b ? a : b; }", "function max(a, b) {\n    return a > b ? a : b;\n}"),
        ("cpp", "python"): ("int minVal(int a, int b) { return a < b ? a : b; }", "def min_val(a, b):\n    return a if a < b else b"),
        ("cpp", "java"): ("int minVal(int a, int b) { return a < b ? a : b; }", "public static int minVal(int a, int b) { return a < b ? a : b; }"),
        ("cpp", "javascript"): ("int minVal(int a, int b) { return a < b ? a : b; }", "function minVal(a, b) { return a < b ? a : b; }"),
        ("javascript", "python"): ("function square(x) { return x * x; }", "def square(x):\n    return x * x"),
        ("javascript", "java"): ("function square(x) { return x * x; }", "public static int square(int x) { return x * x; }"),
        ("javascript", "cpp"): ("function square(x) { return x * x; }", "int square(int x) {\n    return x * x;\n}")
    }

    for (src, tgt) in DIRECTIONS:
        src_code, tgt_code = templates.get((src, tgt), ("// source stub", "// target stub"))
        for i in range(num_pairs_per_direction):
            records.append({
                "source_lang": src,
                "source_code": f"{src_code}  # fn_{i}",
                "target_lang": tgt,
                "target_code": f"{tgt_code}  // fn_{i}",
                "source_dataset": "silver_llm_teacher",
                "is_gold": False
            })

    return records


def main():
    parser = argparse.ArgumentParser(description="Rosetta AI Silver Data Generation")
    parser.add_argument("--dry-run", action="store_true", help="Print cost estimation without making API calls")
    parser.add_argument("--pairs-per-dir", type=int, default=100, help="Number of pairs per language direction")
    parser.add_argument("--model", type=str, default="gpt-4o-mini", help="Teacher LLM model")
    parser.add_argument("--mock", action="store_true", help="Generate mock silver data for offline testing")
    args = parser.parse_args()

    estimate = calculate_cost_estimate(args.pairs_per_dir, args.model)

    print("\n" + "=" * 60)
    print("ROSETTA AI -- SILVER DATA GENERATION ESTIMATE & DRILLDOWN")
    print("=" * 60)
    print(f"Target model:                   {estimate['model']}")
    print(f"Pairs per direction:            {estimate['num_pairs_per_direction']}")
    print(f"Total language directions:       {estimate['total_directions']}")
    print(f"Total target silver pairs:       {estimate['total_pairs']}")
    print(f"Estimated prompt tokens:        {estimate['estimated_prompt_tokens']:,}")
    print(f"Estimated completion tokens:    {estimate['estimated_completion_tokens']:,}")
    print(f"Estimated Input Cost (USD):     ${estimate['estimated_input_cost_usd']}")
    print(f"Estimated Output Cost (USD):    ${estimate['estimated_output_cost_usd']}")
    print(f"TOTAL ESTIMATED API COST (USD): ${estimate['total_estimated_cost_usd']}")
    print("-" * 60)
    print("Directional Pair Breakdown (12 Directions):")
    for dir_name, count in estimate["direction_breakdown"].items():
        print(f"  - {dir_name}: {count} pairs")
    print("=" * 60 + "\n")

    if args.dry_run:
        logger.info("Dry-run complete. Exiting without making API calls.")
        return

    if args.mock:
        logger.info("Generating offline mock silver data...")
        CURATED_DATA_DIR.mkdir(parents=True, exist_ok=True)
        records = generate_mock_silver_pairs(args.pairs_per_dir)
        with open(OUTPUT_SILVER_FILE, "w", encoding="utf-8") as f:
            for r in records:
                f.write(json.dumps(r) + "\n")
        logger.info(f"Wrote {len(records)} mock silver pairs to {OUTPUT_SILVER_FILE}")
        return

    # Check API Key before running real generation
    api_key = os.getenv("GEMINI_API_KEY") or os.getenv("OPENAI_API_KEY") or os.getenv("ANTHROPIC_API_KEY") or os.getenv("HF_TOKEN")
    if not api_key:
        logger.error("No GEMINI_API_KEY, OPENAI_API_KEY, ANTHROPIC_API_KEY, or HF_TOKEN environment variable set.")
        logger.error("Aborting real generation. Use --mock for offline generation or set an API key in .env.")
        return



if __name__ == "__main__":
    main()
